"""Added feedback table

Revision ID: 581b9ec71aee
Revises: 7b9d5f12dbc5
Create Date: 2024-12-01 13:26:43.027136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581b9ec71aee'
down_revision: Union[str, None] = '7b9d5f12dbc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass