"""Added new table

Revision ID: 890220906668
Revises: f462f3058846
Create Date: 2024-11-27 21:19:22.580882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890220906668'
down_revision: Union[str, None] = 'f462f3058846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass