"""Added ne table

Revision ID: b8e4888b43a7
Revises: cc8a8977eb0f
Create Date: 2024-11-25 22:45:01.545559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e4888b43a7'
down_revision: Union[str, None] = 'cc8a8977eb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('speciality', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('next_available', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('patients', sa.String(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('availability', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('awards', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('time_slots', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('specializations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('insurance_accepted', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('hospital_affiliations', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
