"""Added name column

Revision ID: c4f88c89b3b5
Revises: 080b07c00058
Create Date: 2024-11-25 01:17:17.486263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f88c89b3b5'
down_revision: Union[str, None] = '080b07c00058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('requires_prescription', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.drop_index('ix_users_firstname', table_name='users')
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.drop_index('ix_users_lastname', table_name='users')
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.create_index('ix_users_lastname', 'users', ['lastname'], unique=True)
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=True)
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
