"""Added new table

Revision ID: e2a8350b5140
Revises: ea3685bc2358
Create Date: 2024-11-27 23:15:21.870077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a8350b5140'
down_revision: Union[str, None] = 'ea3685bc2358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.Integer(), nullable=False, comment='This is a 6 digit unique join code'),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('join_code')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['join_code'], ['rooms.join_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webrtc_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('offer_details', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['join_code'], ['rooms.join_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webrtc_offers')
    op.drop_table('participants')
    op.drop_table('rooms')
    # ### end Alembic commands ###
