"""Added new table

Revision ID: f462f3058846
Revises: 129c07d1a803
Create Date: 2024-11-27 21:11:37.397049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f462f3058846'
down_revision: Union[str, None] = '129c07d1a803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass